version: "3"

services:
  # The Cookie Factory backend in SpringBoot
  tcf-server:
    image: pcollet/tcf-spring-backend
    container_name: server
    environment:
      - BANK_WITH_PORT=bank-system:9090
      - POSTGRES_HOST=postgres:5432
    # waiting for postgres
    entrypoint: "bash -c '/wait-for-it.sh $${POSTGRES_HOST} -- java -jar /app.jar --bank.host.baseurl=http://$${BANK_WITH_PORT}'"
    depends_on:
      - bank-system
      - postgres

  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres:
    image: postgres:14.2
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=tcf-db

  # A simple java CLI
  tcf-cli:
    image: pcollet/tcf-spring-cli
    container_name: cli
    environment:
      - SERVER_WITH_PORT=tcf-server:8080
    entrypoint: "bash -c '/wait-for-it.sh $${SERVER_WITH_PORT} -- java -jar /app.jar'"
    depends_on:
      - tcf-server
    volumes:
      - ./cli/demo.txt:/demo.txt
    stdin_open: true
    tty: true

  # An external bank service in C#
  bank-system:
    image: pcollet/tcf-bank-service
    container_name: bank
